//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_SMPEntities : DbContext
    {
        public DB_SMPEntities()
            : base("name=DB_SMPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TB_CAT> TB_CAT { get; set; }
        public DbSet<TB_Supp> TB_Supp { get; set; }
        public DbSet<TB_PUR> TB_PUR { get; set; }
        public DbSet<TB_CUS> TB_CUS { get; set; }
        public DbSet<TB_USERS> TB_USERS { get; set; }
        public DbSet<TB_Sell> TB_Sell { get; set; }
    }
}
