using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using WindowsFormsApp.EPL;
using static System.Windows.Forms.VisualStyles.VisualStyleElement.Window;

namespace WindowsFormsApp.PL
{
    public partial class FRM_SUPP : Form
    {
        BL.Methods methods = new BL.Methods();
        DB_SMPEntities db = new DB_SMPEntities();
        TB_Supp TB_SUPP = new TB_Supp();
        int id;
        public FRM_SUPP()
        {
            InitializeComponent();

            WindowsFormsApp.DB_SMPEntities dbContext = new WindowsFormsApp.DB_SMPEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.TB_Supp.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                gridControl1.DataSource = dbContext.TB_Supp.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            //  WindowsFormsApp.DB_SMPEntities dbContext = new WindowsFormsApp.DB_SMPEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.TB_Supp.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                gridControl1.DataSource = dbContext.TB_Supp.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        private void FRM_CAT_Load(object sender, EventArgs e)
        {

        }

        private void gridControl1_Click(object sender, EventArgs e)
        {

        }

        private void button3_Click(object sender, EventArgs e)
        {

        }

        private void gridControl1_Click_1(object sender, EventArgs e)
        {

        }

        private void gridControl1_Click_2(object sender, EventArgs e)
        {

        }

        private void panel2_Paint(object sender, PaintEventArgs e)
        {

        }

        private void btn_add_Click(object sender, EventArgs e)
        {
            FRM_SUPP_ADD fRM_SUPP_ADD = new FRM_SUPP_ADD();
            fRM_SUPP_ADD.id = 0;
            fRM_SUPP_ADD.btn_add.Text = "المورد";
            fRM_SUPP_ADD.Show();
        }

        private void btn_update_Click(object sender, EventArgs e)
        {
            Update_data();
        }

        private void btn_delete_Click(object sender, EventArgs e)
        {
            Toast toast = new Toast();
            Diolag diolag = new Diolag();
            id = Convert.ToInt32(tileView1.GetFocusedRowCellValue("ID"));
            if (id > 0)
            {
                try
                {
                    var rs = MessageBox.Show("عملية حذف", "هل تريد حذف هذا المورد", MessageBoxButtons.YesNo);
                    if (rs == DialogResult.Yes)
                    {
                        TB_SUPP = db.TB_Supp.Where(x => x.ID == id).FirstOrDefault();
                        db.Entry(TB_SUPP).State = System.Data.Entity.EntityState.Deleted;
                        db.SaveChanges();
                        toast.txt_Caption.Text = "تم حذف المورد";
                        toast.Show();
                        Update_data();
                    }
                }
                catch
                {
                    
                }
            }
            else
            {
                diolag.txt_Caption.Text = "لا يوجد مورد لحذفة";
                diolag.Width = this.Width;
                diolag.Show();
            }



        }

        private void Update_data()
        {
            db = new DB_SMPEntities();
            gridControl1.DataSource = db.TB_Supp.ToList();
        }

        private void btn_edit_Click(object sender, EventArgs e)
        {
            Toast toast = new Toast();
            Diolag diolag = new Diolag();
            FRM_SUPP_ADD fRM_SUPP_ADD = new FRM_SUPP_ADD();
            id = Convert.ToInt32(tileView1.GetFocusedRowCellValue("ID"));
            if(id > 0)
            {

                TB_SUPP = db.TB_Supp.Where(x => x.ID == id).FirstOrDefault();
                fRM_SUPP_ADD.edt_name.Text = TB_SUPP.Supp_Name.ToString();
                fRM_SUPP_ADD.edt_email.Text = TB_SUPP.Supp_Email.ToString();
                fRM_SUPP_ADD.edt_phone.Text = TB_SUPP.Supp_Phone.ToString();
                methods.by = TB_SUPP.Supp_Image;
                fRM_SUPP_ADD.pic_Cover.Image = Image.FromStream(methods.Convert_image());
                fRM_SUPP_ADD.id = id;
                fRM_SUPP_ADD.btn_add.Text = "تعديل";
                fRM_SUPP_ADD.Show();
            }
            else
            {
                diolag.txt_Caption.Text = "لا يوجد مورد لتعديل";
                diolag.Width = this.Width;
                diolag.Show();
            }
        }

        private void btn_search_Click(object sender, EventArgs e)
        {
            var _search = edt_search.Text;
            gridControl1.DataSource = db.TB_Supp.Where(x => x.Supp_Name.Contains(_search)).ToList();
        }
    }
}
