using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using WindowsFormsApp.EPL;

namespace WindowsFormsApp.PL
{
    public partial class FRM_CAT : Form
    {
        BL.Methods methods = new BL.Methods();
        DB_SMPEntities db=new DB_SMPEntities();
        TB_CAT TB_CAT = new TB_CAT();
        int id;
        public FRM_CAT()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            WindowsFormsApp.DB_SMPEntities dbContext = new WindowsFormsApp.DB_SMPEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.TB_CAT.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                gridControl1.DataSource = dbContext.TB_CAT.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        private void FRM_CAT_Load(object sender, EventArgs e)
        {

        }

        private void gridControl1_Click(object sender, EventArgs e)
        {

        }

        private void button3_Click(object sender, EventArgs e)
        {

        }

        private void gridControl1_Click_1(object sender, EventArgs e)
        {

        }

        private void gridControl1_Click_2(object sender, EventArgs e)
        {

        }

        private void panel2_Paint(object sender, PaintEventArgs e)
        {

        }

        private void btn_add_Click(object sender, EventArgs e)
        {
            FRM_CAT_ADD fRM_CAT_ADD = new FRM_CAT_ADD();
            fRM_CAT_ADD.id = 0;
            fRM_CAT_ADD.btn_add.Text = "اضافة";
            fRM_CAT_ADD.Show();
        }

        private void btn_update_Click(object sender, EventArgs e)
        {
            Update_data();
        }

        private void btn_delete_Click(object sender, EventArgs e)
        {
            Toast toast = new Toast();
            Diolag diolag = new Diolag();
            try
            {
                id =Convert.ToInt32(tileView1.GetFocusedRowCellValue("ID"));
           var rs= MessageBox.Show("عملية حذف", "هل انت متاكد من عملية الحذف", MessageBoxButtons.YesNo);
           if (rs == DialogResult.Yes)
            {
                    TB_CAT = db.TB_CAT.Where(x => x.ID == id).FirstOrDefault();
                db.Entry(TB_CAT).State = System.Data.Entity.EntityState.Deleted;
                db.SaveChanges();
                    toast.txt_Caption.Text = "تم حذف الصنف";
                    toast.Show();
                Update_data();
            }
            }catch 
            {
                diolag.txt_Caption.Text = "لا يوجد صنف لحذفة";
                diolag.Width=this.Width;
                diolag.Show();
            }
           
            
        }

        private void Update_data()
        {
            db = new DB_SMPEntities();
            gridControl1.DataSource = db.TB_CAT.ToList();
        }

        private void btn_edit_Click(object sender, EventArgs e)
        {
            FRM_CAT_ADD fRM_CAT_ADD = new FRM_CAT_ADD();
            id = Convert.ToInt32(tileView1.GetFocusedRowCellValue("ID"));

            TB_CAT = db.TB_CAT.Where(x => x.ID == id).FirstOrDefault();
           fRM_CAT_ADD.edt_name.Text=TB_CAT.CAT_name.ToString();
            methods.by = TB_CAT.CAT_cover;
            fRM_CAT_ADD.pic_Cover.Image = Image.FromStream(methods.Convert_image());
            fRM_CAT_ADD.id = id ;
            fRM_CAT_ADD.btn_add.Text = "تعديل";
            fRM_CAT_ADD.Show();
        }

        private void btn_search_Click(object sender, EventArgs e)
        {
            var _search=edt_search.Text;
            gridControl1 .DataSource = db.TB_CAT.Where(x=>x.CAT_name.Contains(_search)).ToList();
        }
    }
}
