using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using WindowsFormsApp.EPL;
using static System.Windows.Forms.VisualStyles.VisualStyleElement.Window;

namespace WindowsFormsApp.PL
{
    public partial class FRM_SELL: Form
    {
        BL.Methods methods = new BL.Methods();
        DB_SMPEntities db = new DB_SMPEntities();
        TB_Sell tb_sell = new TB_Sell();
        public int id;
        public FRM_SELL()
        {
            InitializeComponent();



            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext

            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            WindowsFormsApp.DB_SMPEntities dbContext = new WindowsFormsApp.DB_SMPEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.TB_Sell.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                gridControl1.DataSource = dbContext.TB_Sell.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        private void FRM_CAT_Load(object sender, EventArgs e)
        {

        }

        private void gridControl1_Click(object sender, EventArgs e)
        {

        }

        private void button3_Click(object sender, EventArgs e)
        {

        }

        private void gridControl1_Click_1(object sender, EventArgs e)
        {

        }

        private void gridControl1_Click_2(object sender, EventArgs e)
        {

        }

        private void panel2_Paint(object sender, PaintEventArgs e)
        {

        }

        private void btn_add_Click(object sender, EventArgs e)
        {
            FRM_SELL_ADD frm_SELL_ADD= new FRM_SELL_ADD();
            frm_SELL_ADD.id = 0;

            frm_SELL_ADD.btn_add_pur.Text = "اضافة";
            frm_SELL_ADD.Show();
        }

        private void btn_update_Click(object sender, EventArgs e)
        {
            Update_data();
        }

        private void btn_delete_Click(object sender, EventArgs e)
        {
            Toast toast = new Toast();
            Diolag diolag = new Diolag();
           id = Convert.ToInt32(gridView1.GetFocusedRowCellValue("ID"));
            if (id > 0)
            {
                try
                {
                    var rs = MessageBox.Show("عملية حذف", "هل انت متاكد من عملية الحذف", MessageBoxButtons.YesNo);
                    if (rs == DialogResult.Yes)
                    {
                        tb_sell = db.TB_Sell.Where(x => x.ID == id).FirstOrDefault();
                        db.Entry(tb_sell).State = System.Data.Entity.EntityState.Deleted;
                        db.SaveChanges();
                        toast.txt_Caption.Text = "تم عملية الحذف";
                        toast.Show();
                        Update_data();
                    }
                }
                catch
                {
                    
                }
            }
            else
            {
                diolag.txt_Caption.Text = " لا يوجد عملية بيع لحذفها";
                diolag.Width = this.Width;
                diolag.Show();
            }



        }

        private void Update_data()
        {
            db = new DB_SMPEntities();
            gridControl1.DataSource = db.TB_Sell.ToList();
        }

        private void btn_edit_Click(object sender, EventArgs e)
        {
            Toast toast = new Toast();
            Diolag diolag = new Diolag();
            FRM_PUR_ADD fRM_PUR_ADD = new FRM_PUR_ADD();
            id = Convert.ToInt32(gridView1.GetFocusedRowCellValue("ID"));
            if (id > 0)
            {

                //TB_PUR = db.TB_PUR.Where(x => x.ID == id).FirstOrDefault();
                //fRM_PUR_ADD.edt_Name.Text = TB_PUR.Pur_Name;
                //fRM_PUR_ADD.edt_Name_cat.Text = TB_PUR.Pur_Type;
                //fRM_PUR_ADD.edt_cat.Text = TB_PUR.Pur_Cat;
                //fRM_PUR_ADD.edt_supp.Text = TB_PUR.Pur_Supp;
                //fRM_PUR_ADD.edt_details.Text = TB_PUR.Pur_Det;
                //fRM_PUR_ADD.edt_buy.Text=TB_PUR.Pur_Buy.ToString();
                //fRM_PUR_ADD.edt_sell.Text=TB_PUR.Pur_Sell.ToString();
                //fRM_PUR_ADD.edt_qt.Text=TB_PUR.Pur_Qt.ToString();   
                //fRM_PUR_ADD.edt_tbuy.Text=TB_PUR.Pur_Tbuy.ToString();
                //fRM_PUR_ADD.edt_tsell.Text=TB_PUR.Pur_Tsell.ToString();
                //fRM_PUR_ADD.edt_trev.Text=TB_PUR.Pur_TRev.ToString();
                //fRM_PUR_ADD.id = id;
                //fRM_PUR_ADD.btn_add_pur.Text = "?????";
                //fRM_PUR_ADD.Show();
            }
            else
            {
                diolag.txt_Caption.Text = "?? ???? ??????? ??????";
                diolag.Width = this.Width;
                diolag.Show();
            }
        }

            private void btn_search_Click(object sender, EventArgs e)
        {
            var _search = edt_search.Text;
            gridControl1.DataSource = db.TB_Sell.Where(x => x.Sell_Name.Contains(_search)).ToList();
        }
    }
}
